logging:
  level:
    io.github.syakuis: info
    org.hibernate: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.type.descriptor.sql.BasicExtractor: off
    org.hibernate.engine.jdbc.batch.internal.BatchingBatch: off
  file:
    path:
spring:
  main:
    banner-mode: log